// Generated by CoffeeScript 1.3.3
(function() {
  var routes;

  routes = {
    index: {
      pattern: '/'
    },
    show: {
      pattern: '/show/:id'
    },
    user_profile: {
      pattern: '/user/:id/profile',
      test: true
    }
  };

  module.exports = routes;

}).call(this);
